# Generated by Django 4.1.1 on 2022-12-11 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateTimeField(default=datetime.datetime(2022, 12, 11, 16, 17, 52, 870479))),
                ('data_retirada', models.DateTimeField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=100)),
                ('cod_leitor', models.CharField(max_length=5)),
                ('cpf_funcio', models.CharField(max_length=11)),
            ],
        ),
    ]
