# Generated by Django 4.1.1 on 2022-12-11 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_rename_cpf_funcio_reserva_cpf_biblio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data_reserva',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 17, 9, 29, 665683)),
        ),
    ]
