# Generated by Django 4.1.1 on 2022-12-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitar',
            name='autor',
            field=models.CharField(max_length=100),
        ),
    ]
