# Generated by Django 4.1.3 on 2022-11-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=30)),
                ('editora', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=8)),
                ('categoria', models.CharField(max_length=100)),
                ('anoPublicacao', models.CharField(max_length=4)),
            ],
        ),
    ]
