# Generated by Django 4.1.1 on 2023-01-06 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0011_alter_emprestimo_data_devolucao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimo',
            options={'verbose_name': 'Emprestimo'},
        ),
        migrations.AlterModelOptions(
            name='livros',
            options={'verbose_name': 'Livro'},
        ),
        migrations.RemoveField(
            model_name='emprestimo',
            name='tempo_duracao',
        ),
    ]
