# Generated by Django 4.1.1 on 2023-01-23 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0012_alter_emprestimo_options_alter_livros_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='usuario',
        ),
    ]
