# Generated by Django 4.1.1 on 2023-01-23 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0014_livros_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='usuario',
        ),
    ]
