# Generated by Django 4.1.1 on 2023-01-25 00:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0020_livros_emprestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 24, 21, 21, 38, 878295)),
        ),
    ]
