# Generated by Django 4.1.1 on 2023-01-29 03:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0026_alter_emprestimo_data_devolucao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='reservado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 29, 0, 2, 16, 313054)),
        ),
    ]
