# Generated by Django 4.1.1 on 2023-01-29 03:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0027_livros_reservado_alter_emprestimo_data_emprestimo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='reservado',
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 29, 0, 17, 30, 695009)),
        ),
    ]
