# Generated by Django 4.1.1 on 2022-12-05 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bibliotecario',
            new_name='Bibliotecarios',
        ),
        migrations.AlterModelOptions(
            name='bibliotecarios',
            options={'verbose_name': 'Bibliotecario'},
        ),
    ]
